### ISSUE TITLE
can I use your trained model directly

### ISSUE THREAD

**Issue by sixleaves** [Justin-Tan/generative-compression#3]
If I want to compress my pictures, can I use your trained model directly or do I have to train with my own data set?

**Comment by sixleaves** [comment]
I still have doubts. How can I use your model to compress pictures? What format is the compressed picture? If you want to see the compressed picture, you also need to use your model to decompress it.

**Comment by Justin-Tan** [comment]
If you want to compress arbitrary images it would be better to train on the ADE20k dataset rather than the cityscapes dataset. For the ADE20k dataset you will need to write a script that resizes images to 512px width. The compression works by storing the image as a compressed intermediate representation that is restricted to integer values. The channel dimension of this compressed representation determines the compression factor, measured in bits per pixel. The authors choose `C=2,4,8,16` in their paper. From what I understand, you need to use the decoder to retrieve the compressed image. 

I haven't computed the memory footprint of the weight matrices explicitly, but should be fairly large, most likely the whole model is O(100) MB.

You can consult the paper for further details.

**Comment by sixleaves** [comment]
What is the difference between this decoder and the model and how large is the decoder?

**Comment by Justin-Tan** [comment]
The model consists of encoder -> quantizer -> decoder, the decoder is part of the model. I would estimate the size of the decoder weights to be O(100 MB). 

If you want to understand the compression more thoroughly, I recommend reading the paper.

**Comment by sixleaves** [comment]
Thank you very much. I just want to use it directly in the project. I understand that if the decoder is so large, then it is not suitable for us to use in the project unless the number of pictures in the project is more than 10 times that of the decoder.
